matrix:
  NAME:
    - ukhomeofficedigital/cdp-ci
  DOCKER_REPO:
    - quay.io
pipeline:
  docker-build:
    image: docker
    secrets:
      - git_deployment_key
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - echo $(echo $$GIT_DEPLOYMENT_KEY | wc -c)
      - docker build --build-arg "GIT_DEPLOYMENT_KEY=$${GIT_DEPLOYMENT_KEY}" -t ${DOCKER_REPO}/${NAME}:$${DRONE_COMMIT_SHA} .
    when:
      event:
        - pull_request
        - push
        - tag

  docker-build-and-push:
    image: docker
    secrets:
      - docker_username
      - docker_password
    commands:
      - docker login -u="${DOCKER_USERNAME}" -p=$${DOCKER_PASSWORD} ${DOCKER_REPO}
      - docker tag cdp-ci:$${DRONE_COMMIT_SHA} ${DOCKER_REPO}/${NAME}:$${DRONE_COMMIT_SHA}
      - docker tag cdp-ci:$${DRONE_COMMIT_SHA} ${DOCKER_REPO}/${NAME}:latest
      - docker tag cdp-ci:$${DRONE_COMMIT_SHA} ${DOCKER_REPO}/${NAME}:$${DRONE_TAG}
      - docker push ${DOCKER_REPO}/${NAME}:$${DRONE_COMMIT_SHA}
      - docker push ${DOCKER_REPO}/${NAME}:latest
      - docker push ${DOCKER_REPO}/${NAME}:$${DRONE_TAG}
    when:
      event: tag
