matrix:
  NAME:
    - ukhomeofficedigital/cdp-ci
  DOCKER_USERNAME:
    - ukhomeofficedigital+cdp_ci
  DOCKER_REPO:
    - quay.io
pipeline:
  docker-build:
    image: ukhomeoffice/drone-docker
    repo: '${DOCKER_REPO}/${NAME}'
    dry_run: true
    when:
      event: pull_request
  docker-build-and-push:
    image: ukhomeoffice/drone-docker
    secrets: [ docker_password ]
    username: '${DOCKER_USERNAME}'
    repo: '${DOCKER_REPO}/${NAME}'
    registry: '${DOCKER_REPO}'
    auto_tag: true
    when:
      event: tag
